---
title: 'Técnicas de persuasión y convencimiento'
subtitle: 'Miguel Carbonell'
date: '5 de febrero de 2020'
output: pdf_document
---

> La **excelencia** es el arte que se alcanza a través del entrenamiento y el
**hábito**, nosotros somos lo que hacemos repetidamente... La excelencia,
entonces, no es un acto; es un hábito.
>
> Aristóteles.

+ La persuasión es el fondo y la prueba de fuego de la argumentación.
+ No solo se aplica en temas jurídicos sino en las relaciones sociales, que se
    basan cada más en el consenso y menos en la fuerza. Las sociedades se
    hacen más horizontales que antes.
+ Componentes de la persuasión:
    - Agente: persona que busca persuadir.
    - Objetivo: persona a la que se busca persuadir.
    - Tácticas: lo que el agente dice o hace para lograr la persuasión.
    - Contexto: circunstancias en las que se produce el intento de persuasión.
+ Retórica
    - Según los griegos es el arte de la influencia, la amistad, la elocuencia,
        el ingenio y la lógica.
    - La argumentación es la herramienta de la retórica.
    - Artistóteles destacó en la retórica: Retórica, refutaciones sofísticas,
        análisis del silogismo, etc.
+ Tipos de argumentación, según Aristóteles:
    - *Ethos*. Argumentación basada en el carácter.

        * Emplea la personalidad, la reputación y la capacidad de parecer fiable
            de una persona.
        * Se construye a partir del tono, el aspecto y los modales. Los romanos
            lo llamaban *decorum*, que debe ser apropiado para cada auditorio.
            Ellos destacaron el control de la voz, los gestos, la ropa y el
            ritmo de la exposición.

    - *Logos*. Argumentación basada en la lógica.
    - *Pathos*. Argumentación basada en la emoción.

        * Identificar y controlar las propias emociones (ira, frustación,
            hartazgo, prisa, incomodidad, celos, etc.).
        * No responder a las provaciones o ataques de la contraparte.
        * Identificar los intereses de la otra parte: hacerla el centro de
            interés, darle absoluta atención y seguridad psicológica para que
            pueda decir lo que quiera.
        * Algunas **necesidades básicas** de las personas son: seguridad,
            bienestar económico, sentimiento de pertenencia, reconocimiento y
            control sobre la propia existencia. Reconocer estas necesidades de
            nuestra contraparte es útil en un proceso de persuasión y
            convencimiento.
        * También hay que tomar en cuenta el **contexto** (lugar): ruido,
            temperatura, privacidad, facilidad para abandonar el lugar,
            "mejor con una tasa de café".
        * *Kairos* (el arte de esperar el momento perfecto para
            persuadir). **(a)**. Implica buscar el momento y el lugar (relación
            con el contexto y el medio --correo-e, llamada de teléfono,
            conversación cara a cara). **(b).** La palabra escrita es más
            efectiva para una argumentación lógica, mientras que la hablada es
            mejor para apelas a las emociones. **(c).** Hay que poner a jugar
            el tiempo a nuestro favor: no tomar decisiones de inmediato;
            preparar previamente una excusa o razón para levantarse de la mesa;
            el tiempo y la distancia ayudan a tomar mejores decisiones.

        * Lenguaje corporal: contacto corporal, proximidad física, orientación
            espacial, postura corporal (técnica del espejo), ademanes, etc.
            Esto hay que verlo en un contexto cultural, pues cambia de un
            contexto a otro.

+ ¿Cuándo persuadir y cuándo no?
    - Contexto *mercantil* o económico

        * La sociedad acepta que es lícito obtener el mayor beneficio posible.
            Nos regimos por una lógica de oferta y demanda.
        * Se acepta un cierto grado de individualismo.

    - Contexto de *amistad*

        * La sociedad no acepta la lógica del máximo beneficio, pues los amigos
            se procuran un beneficio recíproco.

    - Contexto *sentimental*

+ **Técnica Jujitso**. En vez de responder a los ataques, hay que sacarles
    provecho:
    - Pedir a la otra parte que le explique cómo podría hacerlo mejor.
    - Hacer preguntas en vez de hacer afirmaciones.
    - Usar el silencio como un arma.
    - Mantener el autocontrol.

+ Factores externos de la persuasión:
    - Velocidad: lento o rápido.
    - Formalidad: alta o baja.
    - Acuerdo verbal o por escrito.
    - Temporalidad: corto o largo plazo.
    - Rigidez de los acuerdos: flexibilidad o definitividad.

+ Técnicas de persuasión social
    - **Reciprocidad**. Buen trato hacia los demás; entrega de regalos (*efecto
        retención*), con un mayor efecto si es especial, personalizado e
        inesperado y que pueden ser intangibles (atención, información, tiempo,
        recomendaciones, halagos, etc.)
    - **Autoridad**. Si somos percibidos como expertos en algún tema,
        aumentamos significativamente nuestra capacidad de persuación, pues
        como el mundo es complejo y tiempo limitado, la gente no puede acceder
        a suficiente información y prefiere confiar en la opinión de un experto.
        Para aumentar la credibilidad:

        * No asumir que el otro está entendiendo.
        * Decir la verdad, aunque sea dolorosa.
        * Usar cifras precisas; además, dificultan que la otra parte pueda
            regatear.
        * Tendemos a creerle más a las personas que percibimos exitosas.
        * Si hay alguna debilidad, no esperar a que la otra persona la descubra,
            sino ponerla en la mesa lo antes posible.
        * Conoce tu caso a la perfección.

    - **Compromiso/consistencia**. Podemos persuadir mejor a alguien si
        logramos que haga público un compromiso respecto al tema y, aún más,
        que lo haga público.
    - **Escasez**. Podemos señalar lo que una persona perdería si no se hace el
        compromiso (*sesgo de aversión a la pérdida*); pues puede ser superior
        el miedo a la pérdida que el goce de lo que podría ganar.
    - **Gusto**. Se  pueden generar lazos a partir de gustos comunes; busquemos
        en los demás algo que nos guste, y activamos el mecanismo de la
        reciprcidad. :)
    - **Tendencia social**. Las personas actúan tal como perciben que actúan
        las demás.

+ Estrategia de convencimiento:
    - Ayudar al otro a cantar victoria: no se trata de ganar, sino sólo de
        obtener lo que queremos.

        * Saber conceder es esencial para desarrollar una actitud conciliadora
            que predispone a la otra parte a llegar a un mejor acuerdo.

    - Ayudarle a decir la verdad.
    - Poner muchos asuntos sobre la mesa y no solamente uno.

+ **Método de Henry Kissinger**. Planteaba siempre 5 opciones al tomador de
    decisiones: la primera y la última eran las más extremas; en el medio,
    estaban las que él prefería.

+ Necesidades del abogado
    - Conoce tu caso a la perfección. Supone haber revisado todo lo que forma
        parte de la *litis* o tener relevancia en el curso del proceso. Los
        cursos se ganan con preparación.
    - Enfocar la persuasión. Ser selectivos en la selección de argumentos; es
        mejor desarrollar uno a fondo que extraviar al tribunal con muchos
        argumentos irrelevantes.
    - Cuidar el lenguaje. La forma de decir las cosas incide en nuestra
        capacidad persuasiva.
    - Organizar la forma de presentar las opciones para facilitar que el otro
        elija la opción que queremos.
    - Dar opciones, pero no demasiadas (*parálisis por análisis*).

+ 10 aspectos de una buena argumentación:
    1. Argumentar es, siempre, comunicar (comunicación efectiva, escrita u oral).
    2. Toda buena argumentación parte de un proceso de toma de decisiones
        (¿demando o no?, ¿utilizo un medio alternativo?, etc.)
    3. Para argumentar bien no solo hay que conocer el derecho, sino también los
        hechos alrededor del caso. Los hechos se regien por el principio de
        cuausalidad (causas físicas, biológicas, químicas, etc.) que deben ser
        organizadas y expuestas ante el tribunal.
    4. Una argumentación efectiva descansa en pruebas, no es un concurso de
        opiniones. "Los procesos judiciales no buscan responder a la pregunta
        '¿qué pasó?' sino a '¿qué puedes probar?'". Pruebas testimonial,
        pericial, electrónica, etc.
    5. Toda buena argumentación supone una buena interpretación.
    6. Hay que tener en cuenta la diferente estructura de las normas jurídicas
        que integran el ordenamiento (en unas se aplica la subsunción, en otras
        la ponderación, etc.).
    7. Saber desarrollar una **teoría del caso**: elementos fácticos, normativos
        y probatorios para responder '¿qué paso?'.
    8. Usar todo el arsenal argumentativo disponible: derecho interno e
        internacional, la jurisprudencia interamericana.
    9. Conocer sentencias del juez o tribunal ante el que actuamos e identificar
        el "estilo judicial".
    10. Estudio de la argumentación por medio de casos.
