---
title: Campo Algodonero y caso Ayotzinapa
author: Santiago Botero Sierra
date: 27 de febrero de 2020
---

# Campo Algodonero

+ Responsabilidad internacional del Estado mexicano por la desaparición de y
    ulterior muerte de 3 mujeres (Claudia Ivette González, Esmeralda Herrera y
    Laura Berenice Ramos Monárrez), 2 de ellas menores, cuyos cuerpos se
    encontraron en un campo algodonero en Ciudad Juárez el 6 de noviembre de
    2001.
+ Acusación de la CIDH:
    - Falta de medidas de protección.
    - Falta de medidas de prevención.
    - Falta de respuesta de las autoridades frente a su desaparición.
    - Falta de debida diligencia.
    - Denegación de justicia.
    - Falta de reparación adecuada.
+ Metodología diferente a la utilizada normalmente en un proceso penal clásico.
    - La metodología normal es buscar primero el móvil y después al responsable.
    - La Corte dijo que no se podían entender sin analizar antes el contexto
        del caso.
+ Contexto social:
    - Incremento considerable de mujeres en Ciudad Juárez a partir de 1993.
    - El coeficiente se duplicó el doble en mujeres, en relación con hombres.
    - Es desproporcionadamente mayor que en otras ciudades fronterizas análogas.
    - No hay un número de homicidios claramente establecido (260 a 442). La
        Fiscalía Especial reporta 4,456 mujeres desaparecidas; la CNDH, 2,415.
    - Víctimas: mujeres jóvenes (15-25 años); estudiantes o trabajadoras de las
        maquilas; de escasos recursos económicos; migrantes.
    - Modalidades:

        * Violencia sexual, otros abusos, tortura y mutilación. 26% de casos
            clasificacdos como asesinatos seriales. Hay quienes dicen  que era
            un grupo organizado: privación de la libertad, alimentación, 
            violación y tirado de los cuerpos; esto es por análisis
            periodísticos, incluso hay películas. Se maneja la hipótesis de un
            grupo de empresarios que lo hacía como una especie de parafilia.
        * Otra modalidad son víctimas de la violencia social (31%). Venganza,
            riñas, etc.
        * Un 28% por violencia domésticas (el Estado decía que era el 66%).

    - Contexto de discriminación
