---
title: Campo Algodonero
author: Santiago Botero Sierra
date: 27 de febrero de 2020
---

+ La Corte: (i) analiza el caso, (ii) analiza la actuación de las autoridades y
    (iii) suministra estándares de actuación.
+ Responsabilidad internacional del Estado mexicano por la desaparición de y
    ulterior muerte de 3 mujeres (Claudia Ivette González, Esmeralda Herrera y
    Laura Berenice Ramos Monárrez), 2 de ellas menores, cuyos cuerpos se
    encontraron en un campo algodonero en Ciudad Juárez el 6 de noviembre de
    2001.
+ Acusación de la CIDH:
    - Falta de medidas de protección.
    - Falta de medidas de prevención.
    - Falta de respuesta de las autoridades frente a su desaparición.
    - Falta de debida diligencia.
    - Denegación de justicia.
    - Falta de reparación adecuada.
+ Metodología diferente a la utilizada normalmente en un proceso penal clásico.
    - La metodología normal es buscar primero el móvil y después al responsable.
    - La Corte dijo que no se podían entender sin analizar antes el contexto
        del caso.
+ Contexto social:
    - Incremento considerable de mujeres en Ciudad Juárez a partir de 1993.
    - El coeficiente se duplicó el doble en mujeres, en relación con hombres.
    - Es desproporcionadamente mayor que en otras ciudades fronterizas análogas.
    - No hay un número de homicidios claramente establecido (260 a 442). La
        Fiscalía Especial reporta 4,456 mujeres desaparecidas; la CNDH, 2,415.
    - Víctimas: mujeres jóvenes (15-25 años); estudiantes o trabajadoras de las
        maquilas; de escasos recursos económicos; migrantes.
    - Modalidades:

        * Violencia sexual, otros abusos, tortura y mutilación. **26%** de casos
            clasificacdos como asesinatos seriales. Hay quienes dicen  que era
            un grupo organizado: privación de la libertad, alimentación,
            violación y tirado de los cuerpos; esto es por análisis
            periodísticos, incluso hay películas. Se maneja la hipótesis de un
            grupo de empresarios que lo hacía como una especie de parafilia.
        * Otra modalidad son víctimas de la violencia social (**31%**).
            Venganza, riñas, etc.
        * Un **28%** por violencia domésticas (el Estado decía que era el 66%).

    - Contexto de discriminación sistemática de la mujer. La CIDH no se limita a
        mirar a estas tres mujeres, sino que va más allá y mira el contexto de
        las demás víctimas.
    - Desigualdad de género, que se incrementa cuando la mujer se incorpora al
        mercado de trabajo (rompimiento de roles tradicionales).
+ Pobreza de las investigaciones.
    - Espera de 48 horas, desechamiento.
    - En los primeros años no había expedientes, sino "simples bolsas de huesos"
    - Irregularidades y deficiencias de la investigación. Demora en el inicio,
        lentitud, inactividad de expendientes, negligencia en pruebas,
        negligencia en identificación de las víctimas, pérdida de información,
        extravío de piezas de los cuerpos y falta de análisis de contexto.
    - Discriminación de las autoridades.
    - Revictimización: las autoridades las culpaban por la "falta de moralidad",
        forma de vestir, etc.
    - Inmovilismo. 4/92 delitos sexuales judicializados hasta 2004.

+ Hechos del caso.
    - Claudia Ivette González, 20 años, trabajadora de maquila; llegó 2 minutos
        tarde y no la dejaron entrar, ese día desaparece.
    - Laura Berenice Ramos Monárrez, 17 años, desaparece cuando iba a una fiesta.
    - Esmeralda Herrera Monreal, 15 años, desaparece después de trabajar como
        empleada doméstica.
    - En las primeras 72 horas sólo hubo un registro y se tomó testimonio, pero
        el estado no hizo nada (una investigación material).
    - Después se mandaron a hacer carteles, pero no consta la fecha ni el
        momento y la forma en que se hicieron circular; hubo líneas que no se
        agotaron, pese a estar en las denuncias; falta de comunicación de la
        autoridad y las familias.

+ Estereotipos de la autoridad.
    - Las víctimas propiciaron su propia desaparición y muerte.
    - Se requería a las familias información sobre las preferencias sexuales de
        las víctimas.
    - Desapariciones de "alto riesgo".
+ Hallazgos de los cuerpos
    - Los cuerpos fueron hallados el 6 de noviembre de 2001; al día siguiente se
        hallaron 5 cuerpos adicionales.
    - Las víctimas fueron violadas y abusadas con crueldad.
    - Deficiencias en las autopsias: errores graves en el levantamiento de los
        cuerpos y la realización de la autopsia; se sabe que las víctimas fueron
        mantenidas con vida antes de su asesinato, aunque no se puede determinar
        cuánto tiempo estuvieron privadas de la libertad.

        La Corte suministra estándares de las autopsias (párrafo 310) y analiza
        la incompetencia de las autoridades; con la participación del perito
        Equipo Argentino de Antropología Forense.

+ Deber de prevención.
    - "Los Estados deben generar un entorno físico seguro para  las mujeres, lo
        que incluye adecuada planificación urbana, diseño de  edificios y
        residencias, mejoramiento del transporte público, así como de  los
        caminos que utilizan las mujeres."
    - Se deben tomar: (i) antes de la desaparición de las víctimas y (ii) antes
        de la localización de los cuerpos sin vida.
    - El estado llevó a cabo actos formales y no materiales de búsqueda.
+ Deber de investigar.
    - Cuando se toma conocimiento de una desaparición, se debe iniciar (sin
        dilación) de oficio una investigación (seria, imparcial y efectiva); hay
        deberes reforzados cuando la víctima es una mujer  que puede haber
        sufrido violencia de género.
    - Errores en: levantamiento, falta de preservación de la escena, manejo de
        evidencias e indicios, falta de exhaustividad en recolección de
        indicios y ausencia de cadena de custodia.
    - Errores en la identificación y entrega de los cuerpos; los resultados de
        ADN se entregaron 2 años después.
    - Detuvieron a 2 personas sin relación con los hechos, los acusaron,
        torturaron, mataron a sus abogados defensores, amenazaron a sus
        familiares: uno murió en la cárcel y el otro fue absuelto.
    - 8 años después, las investigacions seguían en "fase preliminar".
    - Los funcionarios responsables estaban en la impunidad; ninguno había sido
        investigado.

+ El Estado se allana a: los errores en las investigaciones adicionales, en la
    integración de las investigaciones, en la identificación de las víctimas,
    en la falta de información puntual respecto al avance de las indagatorias
    realizadas...

+ Reparaciones
    - Debe ser integral y, por las circunstancias del caso, debe tener "vocación
        transformadora".

        * Toda autoridad judicial en México tiene hoy la obligación de
            investigar con perspectiva de género.

    - La Corte da directrices (párrafo 455) para que se conozca la verdad.
    - Se debe sancionar a los funcionarios responsables de las investigaciones.
    - Seguimiento a las denuncias de hostigamiento y persecución de los
        familiares. No fue el presidente ni el secretario
        [Ver](https://www.animalpolitico.com/2011/11/calderon-desdena-acto-sobre-mujeres-muertas-en-campo-algodonero-de-juarez/)
    - Difusión de la sentencia.
    - Reconocimiento público de responsabilidad, transmitido por radio y
        televisión, con presencia de los familiares.
    - Monumento en memoria de las víctimas.
    - Implementación de políticas públicas como garantía de no repetición.
    - Estandarización de protocolos, manuales, criterios de investigación,
        peritajes y demás elementos en casos de violencia contra las mujeres.
    - Estándares internacionales de búsqueda de personas desaparecidas con
        perspectiva de género.
    - Creación y mantenimiento de una página web con datos actualizados de las
        víctimas y personas desaparecidas.
    - Base de datos con información genética de personas desaparecidas a nivel
        nacional.
    - Capacitación continua con perspectiva de género.
    - Atención médica y psicológica a los familiares.
    - Indemnizaciones económicas.
    - Compensación por daño emergente y lucro cesante.
    - Compensación por daño moral.
    - Gastos y costas.

+ Lo que ha pasado después.
    - 2015--2017: 1,640 carpetas de investigación abiertas por feminicidio.
    - Los municipios con más carpetas son Culiacán, Mazatlán, Cajema, Veracruz
        puerto, Navolato y Xalapa.

+ Ciclo de la violencia: fase de tensión, fase de agresión y fase de
    conciliación (luna de miel).

http://www.cineenvioleta.org/la-herencia-de-las-ausentes/
