---
title: Argumentos a favor y en contra del aborto
author: Santiago Botero Sierra
date: 4 de marzo de 2020
---

# Argumentos contra el aborto[^Aclaracion]

[^Aclaracion]: El autor no está de acuerdo con esta postura y considera que
tiene fallas lógicas graves y evidentes.

En diversos tratados internacionales se reconoce que la vida humana es valiosa;
por ello se prohibe la pena de muerte y los tratos crueles. La vida humana
empieza desde la concepción, pues de ella parte un proceso que tiene como
consecuencia, en circunstancias normales, el nacimiento de una persona después
del periodo de gestación. Por lo tanto, el aborto está prohibido por los
tratados internacionales.

La vida humana encarna grandes potencialidades que la sociedad aprovecha:
producción artística, desarrollo científico, liderazgo, etc.; como empieza desde
la concepción, desde entonces la sociedad es acreedora del goce de esas
potencialidades. El aborto es una decisión individual de alguien que no valora
esas potencialidades; la sociedad no debe aceptar ser privada de sus derechos
por el capricho de decisiones individuales. Por lo tanto, la sociedad no debe
aceptar el aborto, pues a través de él un solo individuo le priva del goce de
toda la potencialidad que entraña la vida humana.

La persona que no quiera ser mamá puede tomar decisiones que no implican
sacrificar la vida humana, antes de que la sociedad adquiera sus derechos:
la anticoncepción tiene métodos seguros que le permiten gozar de la sexualidad
sin concebir. Cada quien debe hacerse responsable de sus actos; un acto es
decidir tener relaciones sexuales sin utilizar los métodos anticonceptivos
disponibles y realizarlo puede tener como concuencia lógica una concepción. Por
lo tanto, concebir es la responsabilidad de un acto individual que implica que
quien lo llevó a cabo debe asumir sus consecuencias.

Finalmente, suponiendo que alguien hizo esa acción y aún así se niega a asumir
las consecuencias, eso no implica que la sociedad debe renunciar a sus derechos
si existen alternativas que sean menos gravosas. Hay familias que quieren
adoptar: la adopción permite que la gestante no asuma toda la responsabilidad
por sus decisiones y evita que la sociedad pierda el goce de la potencialidad
humana; por lo tanto, es una alternativa menos gravosa. Entonces, la adopción
debe ser privilegiada frente al aborto por la sociedad.

Entonces, se concluye que una sociedad que respeta el valor de la vida humana,
garantiza la realización de la potencialidad de las personas y reclama su goce,
fomenta la responsabilidad por las decisiones individuales y brinda opciones
como la adopción para los menores sin familias, debe rechazar el aborto.

# Argumentos a favor
    + Un cigoto no es una persona; sólo una manifestación de la voluntad de la
        mujer puede convertirlo en tal.
    + La potencialidad de una nueva vida contra la realización de la vida de la
        mujer.
    + Los métodos no son 100% seguros.
    + Hay muchos niños en adopción que no pueden encontrar hogar; ideas
        atrasadas sobre las identidades de género o la educación homoparental
        impiden que algunos puedan encontrar hogar; hay niños deseados y
        huérfanos que pueden ser adoptados.
