---
title: Clase 4
author: Santiago Botero Sierra
date: 26 de septiembre de 2020
---

+ Artículos 137 y 155, medidas cautelares y oficiosas.
+ Elementos del delito:
	- Elementos positivos del delito: conducta típica, antijuridicidad,
		culpabilidad y punibilidad como consecuencia.
	- Elementos negativos: aticipicidad, causas de justificación, causas de
		inculpabilidad y excusas absolutorias.
	- Estamos en un orden de prelación.

+ Artículo 126.
	- Conducta: Acción o comisión por omisión.
	- Verbo rector: Prive de la vida.
	- Sujeto activo: Calidad específica (madre)
	- Sujeto pasivo: Calidad específica (hijo)
	- Bien jurídicamente tutelado: vida
	- Objeto: jurídico (la vida), material (la persona)
	- Resultado: material
	- Nexo: Causal o por atribuibilidad.
	- Circunstancias: **i)** de tiempo, menos de 24 horas de nacido; o, **ii)**
		de modo.
	- Medios comisivos o de ejecución: ninguno.
	- Subjetivos genéricos: Puede ser doloso o culposo.
	- Elementos volitivos: Ninguno
	- Elementos intelectivos: Ninguno
	- Elementos normativos: vocablo la vida.

+ Invitada: Elisa Vázquez, jueza de control de garantías en la CDMX.
+ Importancia de analizar los tipos penales:
	- Se tiene que acreditar cada uno de estos elementos en una audiencia
		inicial, aunque sea de forma indiciaria.
	- En el juicio esto debe quedar plenamente acreditado.

+ Artículo 127
	-
