---
title: Clase 6
author: Santiago Botero Sierra
date: 10 de octubre de 2020
---

El 10 de octubre de 2020 Ángela Frías prendió el departamento de su vecino,
produjo un incendio y como consecuencia de este el vecino, que estaba dormido,
murió.
	- Previsión: Artículo 123, homicidio (al que prive de la vida a otro) en
		relación con el artículo 138 (homicidio calificado), fracción V (se
		cause por incendio), en relación con el artículo 15 (por acción), artículo 17, fracción I (consumación instantánea), artículo 18, párrafos
		primero (acción dolosa) y segundo (conocer y querer) en relación con
		el artículo 22, fracción I (lo realicen por sí).
	- Sanción: Artículo 128 (veinte a cincuenta años).
	- Clasificación jurídica: Previsión + Sanción.
	- En términos del 141 del CNPP: Homicidio calificado consumado
		instantáneamente donde intervino la autora directa en su forma de acción
		dolosa.

 Previsión: Artículo 123, homocidio (al que prive de la vida a otro)  
 	relación con el artículo 15 (culpa), artículo 17, fracción I (consumación
	instantánea), artículo 18, párrafos primero y tercero (acción, el que produce el resultado típico que no previó siendo previsible) en relación con
	el artículo 22, fracción I (lo realicen por sí).
Sanción: artículo 123 (8 a 20 años), en relación con el 76 (cuarta parte), por
lo que corresponde una sanción de 2 a 5 años de prisión.
