---
title: Clase 3
author: Santiago Botero Sierra
date: 19 de septiembre de 2020
---

+ Dimensiones de la retórica
	- Ethos: Persuade mediante la figura, apariencia, conducta, ejemplo,
		fama y dignidad del que habla.
	- Pathos: Características del que escucha. Es la emoción que se aplica en
		el discurso a través de la técnica del orador; esta emoción despierta
		una respuesta similar en el auditorio.
	- Logos: La fuerza de convicción, que depende de los principios o valores
		de quienes participan en el diálogo.

	Un error en las actuales teorías plantea que los argumentos únicamente
	provienen del logos. Esto es una limitante en la noción originaria de la
	sofística: si bien era la materia y la forma en que se abordaba, el conjunto
	de los elementos se convertían en provisores de argumentos, entonces podemos
	decir que hay argumentos relacionados con cada una de estas dimensiones.

+ El orador, en sentido estricto, es un hombre o mujer elocuenta. Este se hace
	mediante el aprendizaje empírico (basado en la observación de oradores
	elocuentes) o teórico-práctico (por la enseñanza dirigida).
+ Elementos del orador: apostura, voz, formación intelectual, memoria,
	imaginación y recursos oratorios.

+ Apostura. Elementos técnicos
	- Voluntad. Firmeza de caracter para la preparación previa y durante la
		presentación. Los elementos que tiene son: propósito, motivación,
		decisión (afirmaciíon del propósito, planeación y ejecución) y
		perseverancia.
	- Prresencia. Aspectos físicos del orador: forma en que se para, ve al
		público, se viste, etc. Los elementos son: limpieza personal y
		vestimenta adecuada a la ocasión, caminar erguido y con pasos firmes, pararse en forma natural, mantener contacto visual con el público y
		transmitir seguridad y firmeza (control del auditorio).
	- Confianza. Es el elemento más importante, que se relaciona con el control
		del nerviosismo. Tiene dos elementos: confianza en sí mismo
		(conocimiento y experiencias de éxito y confianza en lo que se ofrece) y
		confianza en el público.

+ Más expresividad a los ademanes; bajar más las manos para que se vea más
	fluido. Quizás hay que modular mejor la voz.
