---
title: Clase 4
author: Santiago Botero Sierra
date: 26 de septiembre de 2020
---

+ Manejo de la voz (segundo aspecto técnico del orador)
	- Impostacion (encontrar el tono medio de la voz), gimnasia respiratoria y
		fonación.
	- Vocalización y articulación: vocación, articulación y dicción.
	- Entonación (tono medio de la voz y timbre) y modulación (murmullo,
		volumen medio y plena voz).
+ Licencias métricas
	- Sinalefa: Formar una única sílaba con la última de una palabra que termina
		en vocal y la prímera de una que comienza en vocal.
	- Hiato: Fenómeno contrario a la sinalefa.

+ Formación intelectual
	- Preparación formal y autodidactismo.
	- Hábitos de lectura: libros y textos especializados.
	- Investigación constante.
	- Escucha activa.

+ Memoria
	- Atención, observar atentamente y retener lo que se ve.
	- Asociación: ligar los conceptos, sonidos, imágenes, etc. para fijarlos en
		la memoria.
	- Repetición, ejercitar la atención y la asociación.
+ Imaginación
	- Asociación de objetos o palabras con sucesos
	- Cambio de los personajes de una historia.
+ Recursos oratorios
	- Expresión corporal: movimientos corporales, ademanes y expresión facial.
	- Reacciones ante lo imprevisto.
	- Uso del contexto.
