---
title: Clase 5
author: Santiago Botero Sierra
date: 18 de abril de 2020
---

+ ¿Por qué hay derechos si no están en la Constitución?
    - Positivista
    - Naturalista

+ Avance del naturalismo jurídico después de la Segunda Guerra Mundial
    - No se abandonó el positivismo.
    - Se transformó para evitar que viole los derechos de las personas.
    - Así nace en 1945 la Carta de la ONU, las Naciones Unidas y un proceso de
        entendimiento del derecho.
    - Nacimiento de la Declaración Universal de los Derechos Humanos.
+ Un tribunal especializado, en el siglo XXI, sería inconstitucionalidad.
    - Artículo 14 de la Constitución: una persona puede ser juzgada por un 
        tribunal previamente establecido y por una norma creada con anterioridad
        al hecho.
    - En los juicios de Núremberg la posición naturalista tenía una idea de
        imponer una pena a los participantes, porque la idea era que había que
        castigar el irrespeto a la dignidad de las personas.
    - Estatuto de Roma y su relación íntima con la dignidad humana.
    - Genocidio
+ Constitución positivista de 1917, que incluye "garantías individuales *y
    sociales*". "Derechos fundamentales".

+ Luigi Ferrajoli, neopositivismo (fusión entre el naturalismo y el positivismo)

+ Realismo
    - Norteamericano: parte de la interpretación del juez.
    - Nórdico: Transformación social y aspecto cultural.
+ Teoría de los tres círculos: normas (positivismo), valores (naturalismo) y
    hechos (realismo).

+ Derechos humanos: interdependientes, indivisibles y progresivos.

+ Interpretación: métodos gramatical, teleológico y sistemático.
    - Interpretación conforme: método para armonizar con respecto al derecho
        de los tratados internacionales. Puede pasar que se armonicen las dos
        o se deseche la norma nacional (control de convencionalidad).
    - Interpretación jurídica vs. interpretación constitucional.
