---
title: 'Técnicas de persuasión y convencimiento'
subtitle: 'Miguel Carbonell'
date: '5 de febrero de 2020'
output: pdf_document
---

> La **excelencia** es el arte que se alcanza a través del entrenamiento y el
**hábito**, nosotros somos lo que hacemos repetidamente... La excelencia,
entonces, no es un acto; es un hábito.
>
> Aristóteles.

+ La persuasión es el fondo y la prueba de fuego de la argumentación.
+ No solo se aplica en temas jurídicos sino en las relaciones sociales, que se
    basan cada más en el consenso y menos en la fuerza. Las sociedades se
    hacen más horizontales que antes.
+ Componentes de la persuasión:
    - Agente: persona que busca persuadir.
    - Objetivo: persona a la que se busca persuadir.
    - Tácticas: lo que el agente dice o hace para lograr la persuasión.
    - Contexto: circunstancias en las que se produce el intento de persuasión.
+ Retórica
    - Según los griegos es el arte de la influencia, la amistad, la elocuencia,
        el ingenio y la lógica.
    - La argumentación es la herramienta de la retórica.
    - Artistóteles destacó en la retórica: Retórica, refutaciones sofísticas,
        análisis del silogismo, etc.
+ Tipos de argumentación, según Aristóteles:
    - *Ethos*. Argumentación basada en el carácter.
    
        * Emplea la personalidad, la reputación y la capacidad de parecer fiable
            de una persona.
        * Se construye a partir del tono, el aspecto y los modales. Los romanos
            lo llamaban *decorum*, que debe ser apropiado para cada auditorio.
            Ellos destacaron el control de la voz, los gestos, la ropa y el
            ritmo de la exposición.

    - *Logos*. Argumentación basada en la lógica.
    - *Pathos*. Argumentación basada en la emoción.

        * Identificar y controlar las propias emociones (ira, frustación,
            hartazgo, prisa, incomodidad, celos, etc.).
        * No responder a las provaciones o ataques de la contraparte.
        * Identificar los intereses de la otra parte: hacerla el centro de
            interés, darle absoluta atención y seguridad psicológica para que
            pueda decir lo que quiera.
        * Algunas necesidades básicas de las personas son: seguridad, bienestar
            económico, sentimiento de pertenencia, reconocimiento y control
            sobre la propia existencia.

+ ¿Cuándo persuadir y cuándo no?
    - Contexto *mercantil* o económico

        * La sociedad acepta que es lícito obtener el mayor beneficio posible.
            Nos regimos por una lógica de oferta y demanda.
        * Se acepta un cierto grado de individualismo.

    - Contexto de *amistad*

        * La sociedad no acepta la lógica del máximo beneficio, pues los amigos
            se procuran un beneficio recíproco.
        *

    - Contexto *sentimental*

        *
