---
title: Cuestionario de teoría general del proceso
author: Santiago Botero Sierra
date: 9 de enero de 2021
---

1. **¿Qué entiendes por teoría general del proceso?**

    Creo que es el procedimiento que se debe seguir para llegar a una verdad
    jurídica; es decir, el proceso que se sigue desde que se manifiesta una
    pretensión hasta que se obtiene una determinación firme por parte de un
    órgano jurisdiccional. Creo que puede haber diversos tipos de procesos,
    que dependen de la naturaleza del asunto (civil, penal, constitucional,
    etc.) y que lo *general* en el título de esta asignatura hace referencia a
    que es la base común a dichos procedimientos.

2. **¿Qué te interesa aprender en esta clase?**

    Se que un peligro importante para ganar una pretensión es que, aunque de
    fondo se pueda tener la razón, cualquier omisión en la ejecución del
    procedimiento puede hacer que se pierda el caso. Me gustaría aprender cuáles
    son los elementos básicos de los procedimientos que se deben seguir en
    diversas materias; especialmente, en el ámbito administrativo.

3. **¿Cuáles son tus inquietudes y expectativas de la clase?**

    Mi expectativa es desarrollar los conocimientos básicos del procedimiento
    jurídico que me permitan profundizar en procedimientos específicos más
    adelante. Mi principal inquietud es conocer cuáles son los problemas
    en el procedimiento que harían que se desechara un caso y cuáles, si bien
    no causarían un efecto catastrófico, limitarían las posibilidades de
    alcanzar la pretensión.

4. **¿Qué habilidades pretendes adquirir que te ayudarán en la práctica del
    litigio?**

    Me interesa conocer los procedimientos básicos que hay que tener en cuenta,
    quizás como un diagrama de proceso, que minimicen la posibilidad de que se
    pierda un caso.

5. **¿Te interesa ser abogado litigante? ¿Por qué?**

    Sí, me llama la atención poder defender ante una instancia jurisdiccional
    alguna pretensión para resolver conflictos.
