---
title: Clase con Rosa Calles
author: Santiago Botero Sierra
date: 30 de mayo de 2020
---

+ Opciones laborales
    - Poder ejecutivo
    - Poder legislativo
    - Poder judicial
    - Órganos autónomos

+ Importancia de obtener información sobre el lugar en el cual podemos
    desempeñarnos, especialmente la Constitución, la Ley de la Administración
    Pública Federal y el Reglamento Interior.

+ ¿Cómo puedo trabajar en el gobierno?
    - [Trabajo En](www.trabajaen.gob.mx)
    - [Jóvenes construyendo futuro](jovenescontruyendoelfuturo.stps.gob.mx)
    - Liberación de servicio social
    - Contratación directa o trabajadores de confianza
    - Networking.

+ Alternancia en el gobierno.
    - Podría ocasionar cambios en diversas áreas del trabajo.
    -

+ Averiguar cómo se libera el servicio social mediante el trabajo en el
    gobierno.

+ Enlace legislativo
    - Comisiones
    - Iniciativas
    - Parlamentos abiertos
    - Sesiones

+ [Sistema de Información Legislativa](http://sil.gobernacion.gob.mx/portal)
    - En la Búsqueda avanzada, se puede consultar por tipo de asunto:
        iniciativas, comunicados, etc.
