---
title: Comercio Internacional
subtitle: Secretaría de Economía
author: Santiago Botero Sierra
date: 20 de junio de 2020
---

+ Un Tratado de Libre Comercio es un Tratado Internacional. Un tratado es un
	acuerdo internacional celebrado y escrito entre estados y regido por el
	derecho internacional.
	- Ver la Convención de Viene Sobre Derecho de los Tratados, art. 2.
	- Es un tratado en materia comercial. Es un acuerdo entre dos o más naciones
		para reducir o eliminar barreras comerciales entre países, manteniendo
		barreras contra importadores de otros nacionales.
	- Su intención principal es reducir los aranceles.

+ Negociación de un TLC
	- Ley Orgánica de la Administración pública, art. 34, fracción I.
		Corresponde a la Secretaría de Economía.
	- Reglamento Interior de la Secretaría de Economía, art. 9, fracción II.
		Corresponde a la Subsecretaría de Comercio Exterior "[c]*onducir las
		relaciones y negociaciones comerciales internacionales*".
	- CPEUM.

		* Artículo 89, fracción X, corresponde al presidente dirigir la política
			exterior y celebrar tratados internacionales.
		* Artículo 76, fracción I. Corresponde al Senado aprobar los tratados
			internacionales.
		* Se publica un Decreto de aprobación.

	- Ley sobre la Celebración de Tratados, la parte de tratados de libre
		comercio.

		* Artículo 4. Los tratatos, para ser obligatorios en el territorio
			nacional deberá haber sido publicados previamente en el Diario
			Oficial de la Federación.

	- Ley sobre la aprobación de tratados internacionales en materia económica
		(LATIME). Hace referencia a cuatro comunicaciones: informe de inicio,
		informe periódico, informe sobre el resultado de la negociación, e
		informe y documentos para que el Senado lo apruebe.
+ Cúpulas empresariales. ALACAN, CNA, COPARMIN, etc.

+ Historia
	- 1944, Conferencia de Bretton Woods, para crear el Fondo Monetario
		Internacional y el Banco Internacional para la Reconstrucción y el
		Desarrollo (Banco Mundial).
	- 1947. No sucedió lo anterior, entonces se firma el GATT, para la
		disminución de aranceles.
	- 1947 -- 1993: 8 rondas de negociación del GATT

		* La última fue la Ronda Uruguay 1986 (Uruguay)
		* En el acuerdo de Marrakech (1993) se crea la OMC.
		* 123 países firman la transformación del GATT en la OMC.
		* Es la primera ocasión en que se establece una organización de este
			tipo.

	- Acuerdo de Marrakech (01/01/1995). Tiene anexos

		* Anexo 1A. De mercancías, aranceles y adueneros, agricultura,
			aplicación de medidas sanitarias y fitosanitarias, obstáculos
			técnicos al comercio, salvaguardas.
		* Anexo 1B. Acuerdo sobre el comercio de ser5vicios y anexos.
		* Anexo 1C. Acuerdo sobre aspectos de los derechos de propiedad
			intelectual relacionados con el comercio.
		* Anexo 2. Entendimiento relativo a las normas y procedimientos por los
			que se rige la solución de diferencias.
		* Anexo 3. Mecanismo de examen de las políticas comerciales.
		* Anexo 4. Acuerdos comerciales plurilaterales. Acuerdo sobre el
			comercio de aeronaves civiles (1980), acuerdo sobre contratación
			pública (1996 -- 2014, el revisado viene desde 2014), Acuerdo
			internacional de los productos lácteos (1980 -- 1997), acuerdo
			internacional de la carne de  bovino (1980 -- 1997)
