---
title: Clase de DDHH
author: Santiago Botero Sierra
date: 25 de julio de 2020
---

+ Natalia Pérez Cordero.
	- Defensora de DDHH y académica. Defensa de DDHH desde 2010, Comisión
		Mexicana de Defensa y Promoción de DDHH, búsqueda de los restos de
		Rosendo Radilla; es parte del grupo Fundar.
	- natalia.p.cordero@gmail.com 

+ ¿Qué son los DDHH? Construcción social e histórica, que ha venido
	evolucionando.
	- Amplitud. Se dice que ya hay 5 generaciones de DDHH, que se han venido
		reconociendo en diversas etapas y momentos históricos (civiles y
		políticos; económicos, sociales y culturales; bioéticos y tecnológicos).

+ Defensa de los DDHH
	- Lo que más ha sonado últimamente es la desaparición de personas en México
		y la denuncia de este fenómeno, por parte de las familias y de las
		organizaciones que les acompañan.
	- Ejercicios de poder entre sujetos (Estado y sociedad).
	- Las violaciones por acción suelen estar más vinculadas a los derechos
		civiles y políticos; las violaciones por omisión suelen estar más
		vinculados a los derechos económicos, sociales y culturales.
	- En muchos casos de desaparición no hay certeza del responsable
		(funcionarios del Estado, el narco o una actuación conjunta), también se
		ve combinación entre el poder del Estado y el poder privado en términos
		de derechos ambientales.
	- Por lo tanto, hay una necesidad de generar una defensa de los DDHH y de
		convertirse en defensor de DDHH.
	- El derecho es una herramienta para la defensa de los DDHH, pero esta no se
		limita a estudiar derecho, sino a tener la intención de defender o
		promocionar un DDHH.
	- Para exigir un DDHH, primero se debe conocer.
	- Grupos vulnerables.
	- Defensa institucionalizada y no institucionalizada (organizaciones de la
		sociedad civil institucionalizadas, y defensores de DDHH no
		institucionalizados --defensa en campo o en terreno-).
	- No basta con tener leyes y sentencias de avanzada, si no hay un compromiso
		real por parte de las instituciones y el Estado para la defensa de los
		DDHH. De allí está la importancia de los defensores de DDHH.

+ Desaparición de los años 60 u 80, con un nivel de represión tal que ni
	siquiera se podía denunciar. Estas desapariciones, torturas y ejecuciones
	extrajudiciales se instauraron en una lógica de persecusión. Además, con una
	lógica propagandística que los estigmatizaba y criminalizaba, como forma de
	justificar la desaparición e invisibilizar y negar la situación que se
	estaba presentando.
	- Informe sobre desapariciones en México, emitido en los noventas. Antes de
		eso no existían los recursos ni los mecanismos jurídicos para hacer esta
		clase de denuncias; ello ha mantenido la impunidad.
+ Una segunda tanda de desapariciones se da a partir del 2006, con la guerra
	contra el narco. El primer discurso en esta ola fue nuevamente el intento de
	criminalizar e invisibilizar el problema.

+ Había expectativas diferentes de lo que podría ser este gobierno. Tratándose
	de la defensa estratégica de los DDHH (más allá del litigio estratégico) en
	Fundar ha representado un reto para analizar las políticas y el discurso del
	presidente.
+ El estándar internacional es que un litigio se atienda en un *plazo razonable*
	para llevarlo a una instancia internacional; este plazo está sujeto a
	criterios. Pero un plazo razonable es más de un año normalmente; si hay un
	caso, por ejemplo, de 3 años quizás es poco para nivel internacional. Hay
	que tener una buena documentación del caso y en la narración se describe el
	hecho y el proceso jurídico que se ha intentado agotar para intentar la
	solución a nivel interno. Es muy importante visibilizar cuál es la respuesta
	del estado.
	- Puede haber otras acciones que no son litigio como tal: acciones cautelares
		y llamamientos urgentes a organismos de la ONU, que no son un litigio
		pero sí una llamada de atención para el caso de que se trate.
+ Financiamiento
	- Muchos vienen de empresas que donan de forma altruista.
	- La defensa es muy amplia, hay muchos modelos de defensa, por lo que debe
		haber diferentes mecanismos de financiamiento.
	- Opciones para recibir donaciones directas.
	- "El financiamiento no alcanza para toda la sociedad civil que existe, y la
		sociedad civil que existe tampoco alcanza para todas las víctimas".
	- Los colectivos de mamás de desaparecidos, por ejemplo, hacen sus ventas y
		revenden las donaciones. Otras que ha visto son rifas, recaudación a
		través de plataformas.
+ Desilusión y consejos para atacarla, ¿vale la pena dedicarse de lleno a esto?
	- Es complejo trabajar con personas que han vivido con una situación de
		violencia o de trauma; el hecho de que a uno le guste, es lo que más
		lo puede mantener a uno.
	- Hay un colectivo de búsqueda de fosas clandestinas. Ahí se encontraron
		muchas fosas y cuerpos; son brigadas que se hacen muy grandes. Es una
		experiencia extraña, pero aunque es muy feo y fuerte, al mismo tiempo
		trae esperanza. Es una esperanza que viene desde un lugar muy crudo,
		pero es una forma de esperanza.
	- Las autoridades después no hacen bien su trabajo (no procesan, no hacen
		resguardo, etc.), entonces se pasa a un problema de identificación
		jurídica.
	- Lo primero es tener una convicción de que a uno le gusta este asunto;
		hay que desarrollar mucha resiliencia. Cruza con también tener espacios
		de autocuidado, tanto en lo individual como en lo colectivo; porque
		realmente es frustrante y desgastante el trabajo frente al Estado, te
		lleva a veces a cuestionarse qué tanto vale lo que se logra cuando a
		veces avanzamos muy poco.

+ ¿Cómo empezar? Con voluntariados u organizándose con gente a la que también
	le interese un asunto relevante.
+ Hay estándares e indicadores de evaluación; los más importantes los ha
	desarrollado la ONU.
