---
title: Clase 2
author: Santiago Botero Sierra
date: 16 de mayo de 2020
---

+ Ramas del derecho: Constituional, administrtio, procesal, internacional
    público.

        * Siempre participa al menos una persona de derecho público.

    - Social: Laboral, Agrario, Familiar

        * Orientado a la protección de determinados sectores sociales con
            situación de vulnerabilidad.
        * Familiar: Discusión sobre su autonomía, porque está regulado dentro
            del Código Civil en diversas entidades federativas (incluso en la
            Ciudad de México) pero la tendencia es a separarlo. No obstante,
            está matizada la autonomía de la voluntad y, en algunos casos,
            incluso está derogada.

    - Privado: *Civil* y mercantil.

        * Principio de la igualdad de las partes, la voluntad, dispositivo, etc.
        * Regula las relaciones de poder entre particulares que suponen
            relaciones de coordinación.

+ Derecho civil:
    - Extrapatrimonial: teoría de la ley, derecho de las personas, derecho
        familiar. No hay un contenido económico que sea un fin en sí mismo sino,
        en ocasiones, como un medio para preservar otros valores (por ejemplo,
        la pensión alimentaria persigue la subsistencia de los miembros de la
        familia, a la que no se le puede poner un precio).
    - Patrimonial: derecho de los bienes, las obligaciones y sucesorio.
    - Para algunos autores es equivacada esta división del derecho civil y
        proponen un estudio unitario del derecho civil.

+ Características del derecho civil
    - Es una rama del derecho privado, pues regula relaciones entre
        particulares.
    - Es derecho común, pues regula aspectos básicos del mundo jurídico y es
        supletorio de las otras ramas del derecho.
    - Es derecho sustantivo, pues regula derechos subjetivos, deberes y
        obligaciones.

+ Fuentes (formales) del derecho civil, basado en la pirámide de Kelsen
    - CPEUM y Tratados internacionales sobre DDHH

        * CPEUM

            * Derechos humanos: derechos de la personalidad, igualdad entre
                mujeres  y hombres, reproductivos, al registro, de los niños,
                niñas y  adolescentes, asociación, propiedad.
            * Competencia legislativa en materia civil: cada Estado tiene
                competencia (artículo 124 de la CPEUM), CDMX y Federación.
                Entonces  hay 32 códigos civiles locales y ún código civil
                federal; en las  primeras disposiciones, el Federal dice que se
                trata de asuntos del  orden federal (únicamente), que son
                fundamentalmente aquellos en los  que intervienen autoridades
                federales.
            * Aún no se ha expuesto el Código Único en materia de proceso civil
                y  familiar.

        * Tratados internacionales

            * ONU: Convención sobre derechos del niño: Convención de Naciones
                Unidas sobre el consentimiento para el matrimonio, edad mínima
                para contraerlo y su registro.
            * Sistema interamericano


    - Tratados internacionales de otras materias

        * Ha habido debate sobre si están al mismo nivel de las leyes o no.
        * Hay doctrina que plantea que, como el Estado se comprometió a nivel
            internacional, entonces no puede alegar disposiciones de derecho
            interno, porque el compromiso lo adquiere el estado mexicano en su
            totalidad. El tratado supone compromisos del estado frente a la
            comunidad internacional y las leyes internas deben armonizarse sin
            que esto implique una derogación del tratado internacional.
        * Por lo que hace a nuestra materia, el último criterio de la SCJN es
            que los tratados internacionales sí se encuentran por encima de las
            leyes.

        * En materia procesal civil: Convención interamericana sobre exhortos o
            cartas rogatorias; convención intermaricana sobre eficacia
            extraterritorial de las sentencias y laudos arbitrales extranjeros.
        * Otras materias

    - Código civil y otras leyes

        * Código Civil: Uno Federal y 32 locales.
        * Otras leyes civiles: Ley de propiedad en condominio de inmuebles para
            el Distrito Federal, Ley registral de la Ciudad de México, Ley de
            sociedad de convivencia para la Ciudad de México.

    - Reglamentos

        * Reglamento del Registro Civil del Distrito Federal, Reglamento de la
            ley registral de la Ciudad de México.

    - Jurisprudencia, la emite la SCJN (Pleno o Salas), los Plenos de Circuito
        y los Tribunales Colegiados de Circuito.

    - Costumbre.

        * Tiene un elemento objetivo (*inveterata consuetudo*) y un elemento
            subjetivo (*opinio iuris seu necessitatis*).
        * Tiene dos tipos: derogatoria o *contra legem* (art. 10 CC, nuestro
            sistema rechaza este tipo de costumbre, esta no es fuente del
            derecho en México) y delegada o *praeter legem* (artículos 997 y
            2607 del CC).

    - Doctrina jurídica

        * Es una fuente indirecta que debe ser recogida por una fuente directa.
        * Su función es inspirar la creación, interpretación y aplicación de las
            normas jurídicas civiles.

+ Tarea: Revisar el índice del Código Civil.
