---
title: Clase 8
author: Santiago Botero Sierra
date: 4 de julio de 2020
---

+ Las respuestas del examen era: 1= A, 2= B, 3= C, 4=B, 5= C, 6= B, 7= B, 8= C,
	9=C y 10= A.
+ Patrimonio

+ Derechos patrimoniales (escuela clásica)
 	- Reales: es un poder jurídico que se ejerce
		en forma directa e inmediata sobre un bien, para su aprovechamiento
		total o parcial, y que es oponible a terceros
	- Personales: es una
		relación jurídica entre sujetos de derecho, uno denominado acreedor que
		tiene la facultad de exigir a otro denominado deudor una prestación
		consistente en un dar, hacer o no hacer.

+ Cosas o bienes
	- Art. 747. Pueden ser objeto de apropiación todas las cosas que no están
		excluidas del comercio.
	- Las cosas que están fuera del comercio por su naturaleza o por disposición
		legal (artículo 748) y 749.

	- Según su movilidad: bienes inmuebles o muebles. El artículo 750 dice que
		los muebles son aquellos que por su naturaleza tiendan a estar fijos
		(frac. I a III), por su naturaleza están destinados a la explotación de
		un inmueble y que no pueden separarse sin provocar daño (frac. IV a XI y
		XIII), por el objeto al que se aplican son los derechos reales que
		recaen sobre  inmuebles (como usufructo, uso, habitación, servidumbre o
		hipoteca, fracc. XII) o por la ley (frac. XI y XII). Los bienes
		muebles también lo son por su naturaleza (art. 735) o por determinación
		de la ley (arts. 754 a 759)
	- Según su posibilidad de sustitución: bienes fungibles (quellos que pueden
		ser reemplazados por otros de la misma especie, calidad y cantidad,
		art. 763) o no fungibles (aquellos que no pueden ser reemplazados por
		otros de la misma especie, calidad o cantidad, art. 763).
	- Según las personas a quienes pertenecen: bienes del dominio del poder
		público (aquellos que pertenecen a la Federación, Ciudad de México,
		Estados o Municipios, art. 765, bienes de uso común, art. 768, bienes
		destinados a un servicio público, art. 770 o bienes propios, art. 770);
		o bienes de propiedad de particulares (aquellos cuya propiedad y dominio
		les pertenece legalmente y de las que no puede aprovecharse ninguno
		sin consentimiento del dueño o autorización de la ley, art. 772).
	- Según la incertidumbre sobre su dueño: mostrencos (muebles abandonados o
		perdidos cuyo dueño se ignore, art. 774, sobre los que hay que seguir el
		procedimiento de los arts. 775 a 783) o vacantes (inmuebles que no
		tienen dueño cierto o conocido, art. 785, sobre los que hay que seguir
		el procedimiento de los arts. 786 a 789).

+ Ver: Justicia para los animales, de Pablo de Lora.
