---
title: Clase 13
author: Santiago Botero Sierra
date: 10 de agosto de 2020
---

+ Régimen de las entidades
	- Artículo 116
	- En cada entidad federativa debe haber un órgano encargado de fiscalizar,
	 	de proteger los datos.
	- Prohibiciones absolutas (artículo 117) y relativas (artículo 118).
	- El artículo 120 manda que los gobernadores publiquen las leyes federales.
	- El artículo 121 establece que en cada entidad se le dará validez a los
		actos públicos ejercidos en otras entidades.

+ Régimen de la Ciudad de México
	- Artículo 44, establece que la Cdmx es la capital de la república.
	- Artículo 122

+ Régimen de los municipios
	- Artículo 115

+ Facultades residuales para las entidades federativas (artículo 124).

+ Régimen de responsabilidades de los servidores públicos
	- Artículos 108 a 114
	- Artículo 108, párrafo segundo, el Presidente sólo puede ser acusado de
		traición a la patria o "delitos graves del fuero común".
	- Juicio político (artículos 109 y 110); las sanciones son separación del
		cargo e inhabilitación. Quien conoce es la Cámara de Diputados (cámara
		de instrucción), que acusa ante la Cámara de Senadores (que se erige
		como jurado de sentencia).
	- Otra figura es la *declaración de procedencia* (en lenguaje vulgar se
		conoce como *desafuero*), que se usa cuando un funcionario público es
		acusado de haber cometido un delito.
