---
title: Clase 6
author: Santiago Botero Sierra
date: 22 de junio de 2020
---

+ Principio de soberanía popular y artículo 39 de la CPEUM.
	- El sujeto de la soberanía es el pueblo. Proviene de la filosofía de
		Rosseau, donde la titularidad de la soberanía pertenece al pueblo.
		Asimismo, el poder público proviene del pueblo.
	- Recordar que el poder constituyente desaparece cuando crea la constitución
		y quedan los poderes constituidos; estos no pueden disponer de la
		Constitución, sino únicamente reformarla ateniéndose a las vías y
		procedimientos establecidos en la propia Constitución.
	- El artículo 136 de la CPEUM prohibe el derecho a la revolución: si no
		estamos de acuerdo con algo, lo que se debe hacer es reformar la
		Constitución.
	- En el artículo 40 de la CPEUM señala que es voluntad del pueblo mexicano
		constituirse con cinco características:

		* República: Recordar que se opone a la monarquía, en términes de la
		 	transmisión del poder y de la duración en el ejercicio del poder;
		* Representativa: Recordar que la democracia puede ser directa o
			representativa;
		* Democrática: Hay una relación recíproca entre derechos humanos y
			democracia, y también está el debate sobre la forma de elección de
			nuestros representantes;
		* Laica: Es una característica reciente que implica que hay una
			separación entre el poder político y el poder eclesiástico (Thomas
			Jefferson plantea que tiene que haber un muro de separación entre
			el estado y la religión), la incorporación de la palabra laica es
			reciente, aunque la separación de Iglesia y Estado viene desde las
			Guerras de Reforma, aunque esto se incorpora a nivel constitucional
			en el constituyente de Querétaro; y,
		* Federal. Ver la tesis 163197, sobre las constituciones de los estados.
	- El artículo 41 de la CPEUM dice que el pueblo ejerce su soberanía por
	 	medio de los poderes de la Unión y de los Estados.

+ División de poderes
	- Artículo 49: Legislativo, Ejecutivo y Judicial. Únicamente hay salvedades
		en el artículo 29.
	- Facultades del Ejecutivo: extraordinarias acorde al artículo 29, artículo
		131, párrafo 2.
	- Revisar las tesis 189106, 189109 y 189110.
