---
title: Clase 11
author: Santiago Botero Sierra
date: 29 de julio de 2020
---

+ Principio de taxatividad en materia penal
	- Artículo 14 de la CPEUM.
	- Mandato de cualidad lingüística, que se puede aplicar tanto al supuesto
		de hecho (descripción de la conducta) como a la consecuencia jurídica
		(la pena o sanción del supuesto de hecho).
	- Características de la ley penal taxativa: **i)** respecto de la acción,
		debe ser exterior y empíricamente visible; **ii)** respecto del efecto
		de la conducta, debe consistir en un daño tangible; y, **iii)** respecto
		de la culpabilidad, debe permitir la adscripción causal de la acción a
		la persona que la lleva a cabo.
	- No se puede imponer una pena por analogía ni por mayoría de razón.
	- El cuarto párrafo determina un orden de prelación: la letra de la ley,
		la interpretación jurídica, o los principios generales del derecho.
	- Concepto del debido proceso, Tesis 2005716.
	- Párrafo segundo, actos privativos.

+ Artículo 15 de la CPEUM
	- Sobre la extradición.

+ Artículo 16
	- Primer párrafo, actos de molestia.
	- Molestia de: personas, familias, domicilios, papeles o posesiones.
	- Fundamentación y motivación. Tesis 173565 y 175082.
	- Distinción: detención en flagrancia, detención por caso urgente, detención
		por orden judicial de aprehensión.
	- Tesis 2008638.
	- Amparos directos en revisión 1596/2014, 3463/2012 y 6395/2015, y
	 	contradicción de tesis 312/2016.
