---
title: Clase 8
author: Santiago Botero Sierra
date: 1 de julio de 2020
---

+ Derecho de libertad reproductiva
	- Artículo 4, párrafo 2, de la CPEUM: libertad reproductiva.
	- Como derecho de libertad que es, este artículo despliega sus mandatos
		hacia el legislador. El legislador puede emitir dos tipos de
		disposiciones legislativas: **i)** la prohibición de cualquier ejercicio
		de la sexualidad en contra de la libertad de la persona, **ii)**
		imposibilidad, en términos generales, de la penalización absoluta de la
		interrupción voluntaria del aborto.
	- Hay argumentos de que el producto del embarazo, en algún momento, se
		convierte en un bien jurídico tutelado.
	- Laurence Tribe, *El choque de absolutos*.
	- Ver la sentencia Roe vs. Wade
	- En México se han implementado dos vías: **i)** El legislador puede
		despenalizar el aborto, o **ii)** el ataque a través de amparos; lo
		cierto es que la Suprema Corte aún no se ha pronunciado con
		contundencia.
	- Amparo en revisión 1388/2015, Acción de inconstitucionalidad 10-2000,
		Amparo directo en revisión 183/2017, Caso Artavia Murillo contra Costa
		Rica, amparo en revisión 852-2017.

+ Libertad de trabajo
	- Art. 5
	- Se puede entender que todo trabajo es lícito cuando no viola un derecho
		humano.
	- No hay trabajo obligatorio
	- Algunas profesiones requieren un título profesional para su ejercicio.
		Esto es una habilitación legislativa para que se contemplen las
		profesiones en la ley.
	- La jurisprudencia ha dicho que la regulación de la libertad de trabajo
		corresponde al legislativo (reserva de ley), no puede prohibir un
		trabajo para una sola persona (generalidad y abstracción), los
		reglamentos no pueden establecer requisitos de distancia entre
		establecimientos mercantiles, las sanciones administrativas para
		servidores públicos que consistan en una inhabilitación no viola la
		libertad de trabajo.

+ Libertad de expresión
	- Artículo 6, párrafo primero de la CPEUM, y artículo 13 de la CADH
	- Autorrealización, participación democrática.
	- Los límites a la libertad de expresión están, por un lado, en el discurso
		de odio (art. 20, Pacto Internacional de Derechos Civiles y Políticos),
		insultos, protección de los menores (art. 13, párrafo 4, CADH),
		derecho al honor y a la vida privada,
	- Caso Brandengurg vs. Ohio, Citizens United v. FEC, Texas v. Johnson,
		New York Times v. Sullivan (el debate público debe ser abierto, robusto
		y deshinibido).
	- Amparto directo 28/2010, amparo directo en revisión 2806/2012, amparo
		directo en revisión 6175/2018, amparo directo en revisión 172/2019 y
		Olmedo Bustos vs. Chile.
