---
title: Clase 9
author: Santiago Botero Sierra
date: 8 de julio 2020
---

# Libertad de reunión y asociación

+ Las libertades de reunión y asociación están establecidas en el artículo 9
	de la CPEUM.
	- Sobre la licitud no se puede utilizar el artículo 1830 del CC, porque
		estaríamos privando a la Constitución de su supremacía.
	- Se presume que cualquier reunión tiene un objeto lícito, a menos que
		choque con otro derecho; ese sí sería un límite a la libertad de
		reunión. Podría chocar contra: libertad de tránsito, derecho a la
		propiedad.
	- Ya hay límites en el mismo artículo: si la reunión es armada; profiere
		injurias, hace uso de la violencia o amenaza intimidar a la autoridad.
	- Algunos autores plantean que es una forma de ejercer la libertad de
		expresión.
	- Cuando se ejerce en una vía pública hay que diferenciar entre bloqueo
		(deterse en una vía de comunicación, está prohibido y sancionado por
		los códigos penales) y no bloqueo (que se permita en alguna medida la
		libertad de tránsito).
	- El deber de la policía es: hacer lo que esté a su alcance para que se
		puedan movilizar quienes no se estén manifestando; y garantizar la
		seguridad de las personas.
	- Ley de Movilidad de la Ciudad de México, sentencias que resuelven las
		acciones de inconstitucionalidad 96/2014 y 97/2014.

+ Libertad de asociación
	- La diferencia entre la reunión y la asociación es que el ejercicio de la
		libertad de asociación crea una personalidad jurídica diferente a la de
		quienes integran la asociación.
	- Derechos a afiliarse, salirse ("derecho a la puerta") y permanecer en la
	 	asociación; estos dependen de los requisitos de la asociación.
	- En materia sindical también se dio el fenómeno de las cláusulas de
		inclusión y expulsión. Se compraba a los sindicatos para que este
		hiciera el trabajo sucio.

+ Considerar la relación entre esta mención general en el artículo 9 y las
	modalidades en materia política (conformación de partidos políticos de los
	ciudadanos, art. 41) y en materia laboral (los trabajadores y los patrones,
	art. 123).

+ Libertad de tránsito y residencia están consignados en el artículo 11 de la
	CPEUM.
	- Sobre la libertad de residencia hay limitaciones respecto a la legislación
		en materia de asentamientos humanos.
	- El asilo y el refugio es una especie de deferencia del Estado para recibir
		a personas que corren peligro en su país. México tiene una larga
		tradición diplomática de dar asilo y refugio; la política debe ser de
		puertas generosa. La migración nutre, no empobrece a los países; México
		es muy grande, cabemos todos.

+ Libertad religiosa
	- Artículos 24 y 130 de la CPEUM. El segundo trata no solamente del derecho
		humano sino también del principio histórico de separación entre la
		Iglesia y el Estado.
	- En el constitucionalismo mexicano ha habido normas llamativas: en la
		Constitución de 1814 se decía en el artículo 1 que sólo la religión
		católica estaba permitida en el Estado y, en el artículo 15, que la
		calidad de ciudadano se pierde por heregía, apostasía y lesa nación.
